### PR TITLE
Layout improvements, county charts

### PR DESCRIPTION
**Pull request by vincerubinetti**
- frontend:
  - change "avg" to "state" (perhaps won't always be an average, might be median or mode)
  - update endpoint return types to include state-wide value and source
  - remove custom calculation of min/max/avg/median/etc, and instead use min/max/state values from backend directly
  - tweak banner component, make dismiss button more prominent
  - add bar chart component with ability to display continuous number values and discrete/enumerated string values
  - combine map legends all into one. make scale gradient horizontal, remove labels where possible, add source
  - hide map legend when map popup is open
  - add charts for select measures on county page, and tweak styling of page
  - combine welcome section on home page with banner at top
  - move "data suppression" note down, and also show when any "no data" feature is on map
  - move feedback and cite buttons to under map, and add "click" note
  - tweak tooltips
  - tweak number formatting
- backend:
  - change "avg" to "state" 
  - add `state` and `source` to `/fips-value`
  - hard-code `state_value` instead of calculating it

### CODE REVIEW

**Comment by falquaddoomi** [comment]
> change "avg" to "state"

Great change, thanks!

> TODO: add state and source to /fips-value

So, I have the source data, but in the process of integrating it I had to update the database to the latest CancerInFocus data release, 2024-09, which changes some of the supported columns. Just FYI, I plan to add the updated CiF metadata and the 2024-09 data release as a db dump in this PR. This partially covers #94, but I plan to add the testing fixes and what few tests I've written so far in a separate PR.

> TODO: hard-code state_value instead of calculating it

I wonder if we only display the manually curated sate data and nothing else, or do we use computed values where no curated value exists. I'm leaning toward just using curated data since I'd rather be correct than complete, but I'm open to different opinions. Also, I suppose we're waiting on that data, or was it provided to us? I can look for it if you don't know off the top of your head, but I thought I'd ask.

**Comment by vincerubinetti** [comment]
> I'd rather be correct than complete

This was my feeling as well. It also takes the burden off of us to be accurate data wranglers/scientists. I was getting a little uncomfortable trying to decide what stats to show in the frontend and when.

Regarding your second comment:

I did notice that Jake had requested breast cancer mortality and realized we'd need to add some mechanism to specify or select factors in the `/by-county` endpoint (unless we can convince them we don't need that in the chart).

> I believe the frontend resolves this issue...

Is this paragraph referring to how the frontend selects a factor by default on the home page? Because on the county page there's no magic at all going on in the frontend, I'm just reporting what the endpoint returns.

As such, my first thought was to just return the values for all the possible factor combinations for each measure. I could imagine them asking us to add another factor to the charts, at which point we'd want the frontend to just easily be able to select new ones, e.g. `["scpincidence", "Colon & Rectum", "sex=female;age=50+"],` in `basic-measures.json`. Returning all the factors would probably be a lot of data though.

You could also try to "smartly" decide which factor is relevant for each measure, though that seems more error prone in the long run. And then I'm worried it will require backend modifications to return multiple factors if/when they ask for more.

**Comment by vincerubinetti** [comment]
>  would you prefer I do the factor value resolution silently in the backend, or would you prefer I report additional data in the by-county endpoint about which specific factor values were used for each measure?

This is probably something we'd need to ask the group about. Under the "All" display (as opposed to the "Basic"), I would think it'd be fine to just show whatever the default factors are for each measure (usually "all" but I guess in some cases it's e.g. "sex=female" where no other data exists), but they might want something different.

Not sure what the best course of action is for all of this.

**Comment by falquaddoomi** [comment]
FYI, in commit [3421203](https://github.com/colorado-cancer-center/ecco/pull/95/commits/3421203e2b8f4c1e6ca3c3f9212ce473650bcd3c) I ended up adding `source` and `source_url` to both the `/stats/measures` and `/stats/by-county/` endpoints, both of which are optional strings. I also added `unit` to the `/stats/measures` endpoints, since it seems like it'd be desirable for it to be in there, too.

**Comment by vincerubinetti** [comment]
When going to the county page, I'm getting this server error. I'm guessing if I do a teardown this will go away, but this time I will wait until you can take a look to troubleshoot.

<details><summary>logs</summary>

```shell
(base) Vincents-MacBook-Pro:ecco vincerubinetti$ git pull
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 41 (delta 33), reused 41 (delta 33), pack-reused 0 (from 0)
Unpacking objects: 100% (41/41), 6.94 MiB | 10.31 MiB/s, done.
From github.com:colorado-cancer-center/COCancerScope
   9d36259..02b381e  frontend-enhancements -> origin/frontend-enhancements
Updating 9d36259..02b381e
Fast-forward
 backend/app/commands/import_scp_data.py         |  19 +-
 backend/app/commands/reconcile_codebook_meta.py | 273 ++++++++++++++++++++++++
 backend/app/models/cif_meta.py                  | 353 ++++++++++++++++++++++++++++---
 backend/app/routers/statistics.py               | 140 +++++++++++-
 backend/app/tools/accessors.py                  |   6 +
 db-exports/ecco_2024-09-18.dump                 | Bin 0 -> 7202238 bytes
 6 files changed, 747 insertions(+), 44 deletions(-)
 create mode 100755 backend/app/commands/reconcile_codebook_meta.py
 create mode 100644 db-exports/ecco_2024-09-18.dump
(base) Vincents-MacBook-Pro:ecco vincerubinetti$ ./run_stack.sh 
* Using target environment dev
* Running command: docker compose -f docker-compose.yml -f docker-compose.override.yml up --build
[+] Building 1.6s (32/32) FINISHED                                    docker:desktop-linux
 => [frontend internal] load build definition from Dockerfile                         0.0s
 => => transferring dockerfile: 154B                                                  0.0s
 => [frontend internal] load metadata for docker.io/library/node:21                   0.9s
 => [db internal] load build definition from Dockerfile                               0.0s
 => => transferring dockerfile: 885B                                                  0.0s
 => [db internal] load metadata for docker.io/postgis/postgis:15-3.4                  0.8s
 => [db internal] load .dockerignore                                                  0.0s
 => => transferring context: 2B                                                       0.0s
 => [frontend internal] load .dockerignore                                            0.0s
 => => transferring context: 52B                                                      0.0s
 => [db 1/4] FROM docker.io/postgis/postgis:15-3.4@sha256:9d1ce61fc31803599b2b2df24d  0.0s
 => [db internal] load build context                                                  0.0s
 => => transferring context: 77B                                                      0.0s
 => [frontend 1/6] FROM docker.io/library/node:21@sha256:4b232062fa976e3a966c49e9b62  0.0s
 => [frontend internal] load build context                                            0.0s
 => => transferring context: 39.51kB                                                  0.0s
 => CACHED [db 2/4] RUN mkdir /docker-entrypoint-postinit.d                           0.0s
 => CACHED [db 3/4] COPY ./healthcheck.sh /opt/healthcheck.sh                         0.0s
 => CACHED [db 4/4] COPY ./patched-entrypoint.sh /usr/local/bin/docker-entrypoint.sh  0.0s
 => [db] exporting to image                                                           0.0s
 => => exporting layers                                                               0.0s
 => => writing image sha256:c38fa89a95a87d318eb1bda33f8ca6536ea722a754718c437d731df4  0.0s
 => => naming to docker.io/library/ecco-db                                            0.0s
 => CACHED [frontend 2/6] RUN npm install -g bun@1.0.35                               0.0s
 => CACHED [frontend 3/6] WORKDIR /app                                                0.0s
 => CACHED [frontend 4/6] COPY package.json bun.lockb  ./                             0.0s
 => CACHED [frontend 5/6] RUN bun install                                             0.0s
 => [frontend 6/6] COPY . .                                                           0.1s
 => [frontend] exporting to image                                                     0.0s
 => => exporting layers                                                               0.0s
 => => writing image sha256:97e66f1a5e5e013224ceca8608e32401609ab06a1ee7948a8f214cce  0.0s
 => => naming to docker.io/library/ecco-frontend                                      0.0s
 => [backend internal] load build definition from Dockerfile                          0.0s
 => => transferring dockerfile: 373B                                                  0.0s
 => [backend internal] load metadata for docker.io/library/python:3.10                0.3s
 => [backend internal] load .dockerignore                                             0.0s
 => => transferring context: 2B                                                       0.0s
 => [backend stage-0 1/7] FROM docker.io/library/python:3.10@sha256:08a49662edbfff8a  0.0s
 => [backend internal] load build context                                             0.0s
 => => transferring context: 339.01kB                                                 0.0s
 => CACHED [backend stage-0 2/7] RUN apt-get update && apt-get install -y gdal-bin    0.0s
 => CACHED [backend stage-0 3/7] COPY ./requirements.txt /tmp/requirements.txt        0.0s
 => CACHED [backend stage-0 4/7] RUN --mount=type=cache,target=/root/.cache/pip       0.0s
 => CACHED [backend stage-0 5/7] COPY ./start_app.sh /opt/start_app.sh                0.0s
 => CACHED [backend stage-0 6/7] WORKDIR /app                                         0.0s
 => [backend stage-0 7/7] COPY ./app/ /app                                            0.0s
 => [backend] exporting to image                                                      0.0s
 => => exporting layers                                                               0.0s
 => => writing image sha256:721281f689c6d19fe41992be8202fb675e3a3f12a7a226e1f01b0ae5  0.0s
 => => naming to docker.io/library/ecco-backend:latest                                0.0s
[+] Running 2/4
 ✔ Container ecco-memcached-1  Running                                                0.0s 
 ⠦ Container ecco-frontend-1   Recreated                                             10.6s 
 ✔ Container ecco-db-1         Running                                                0.0s 
 ⠦ Container ecco-backend-1    Recreated                                             10.6s 
Attaching to backend-1, db-1, frontend-1, memcached-1
frontend-1   | $ vite --host 0.0.0.0 --port 8001
frontend-1   | 
frontend-1   |   VITE v5.3.4  ready in 222 ms
frontend-1   | 
frontend-1   |   ➜  Local:   http://localhost:8001/
frontend-1   |   ➜  Network: http://172.18.0.3:8001/
backend-1    | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
backend-1    | INFO  [alembic.runtime.migration] Will assume transactional DDL.
backend-1    | INFO:     Will watch for changes in these directories: ['/app']
backend-1    | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
backend-1    | INFO:     Started reloader process [20] using StatReload
backend-1    | INFO:     Started server process [22]
backend-1    | INFO:     Waiting for application startup.
backend-1    | INFO:     Application startup complete.
db-1         | 2024-09-20 04:40:19.871 UTC [65] LOG:  checkpoint starting: time
backend-1    | INFO:     192.168.65.1:27470 - "GET /locations HTTP/1.1" 200 OK
backend-1    | INFO:     192.168.65.1:27469 - "GET /stats/measures HTTP/1.1" 200 OK
backend-1    | Processing SociodemographicsCounty for measure Total
backend-1    | INFO:     192.168.65.1:27470 - "GET /stats/county/sociodemographics/fips-value?measure=Total HTTP/1.1" 200 OK
backend-1    | INFO:     192.168.65.1:27469 - "GET /counties HTTP/1.1" 200 OK
db-1         | 2024-09-20 04:41:33.491 UTC [65] LOG:  checkpoint complete: wrote 716 buffers (4.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=73.474 s, sync=0.014 s, total=73.619 s; sync files=50, longest=0.003 s, average=0.001 s; distance=5507 kB, estimate=6463 kB
frontend-1   | 4:44:23 AM [vite] hmr update /src/pages/home/SectionMap.vue
frontend-1   | 4:44:30 AM [vite] hmr update /src/components/AppLink.vue
frontend-1   | 4:44:34 AM [vite] hmr update /src/components/AppLink.vue
frontend-1   | 4:44:43 AM [vite] hmr update /src/pages/home/SectionMap.vue
frontend-1   | 4:44:49 AM [vite] hmr update /src/pages/home/SectionMap.vue
frontend-1   | 4:46:15 AM [vite] hmr update /src/components/AppLink.vue
backend-1    | INFO:     192.168.65.1:27813 - "GET /counties HTTP/1.1" 200 OK
backend-1    | INFO:     192.168.65.1:27812 - "GET /stats/by-county/08051 HTTP/1.1" 500 Internal Server Error
backend-1    | ERROR:    Exception in ASGI application
backend-1    | Traceback (most recent call last):
backend-1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
backend-1    |     result = await app(  # type: ignore[func-returns-value]
backend-1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
backend-1    |     return await self.app(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
backend-1    |     await super().__call__(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
backend-1    |     await self.middleware_stack(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-1    |     raise exc
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-1    |     await self.app(scope, receive, _send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-1    |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-1    |     await self.app(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-1    |     raise exc
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-1    |     await self.app(scope, receive, sender)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
backend-1    |     raise e
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
backend-1    |     await self.app(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
backend-1    |     await route.handle(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
backend-1    |     await self.app(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
backend-1    |     response = await func(request)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
backend-1    |     content = await serialize_response(
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 154, in serialize_response
backend-1    |     raise ResponseValidationError(
backend-1    | fastapi.exceptions.ResponseValidationError: 12 validation errors:
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'aac'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'state_aac'), 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'order'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'aac'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'state_aac'), 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'order'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    | 
backend-1    | INFO:     192.168.65.1:27825 - "GET /counties HTTP/1.1" 200 OK
backend-1    | INFO:     192.168.65.1:27824 - "GET /stats/by-county/08051 HTTP/1.1" 500 Internal Server Error
backend-1    | ERROR:    Exception in ASGI application
backend-1    | Traceback (most recent call last):
backend-1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
backend-1    |     result = await app(  # type: ignore[func-returns-value]
backend-1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
backend-1    |     return await self.app(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
backend-1    |     await super().__call__(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
backend-1    |     await self.middleware_stack(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-1    |     raise exc
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-1    |     await self.app(scope, receive, _send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-1    |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-1    |     await self.app(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-1    |     raise exc
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-1    |     await self.app(scope, receive, sender)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
backend-1    |     raise e
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
backend-1    |     await self.app(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
backend-1    |     await route.handle(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
backend-1    |     await self.app(scope, receive, send)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
backend-1    |     response = await func(request)
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
backend-1    |     content = await serialize_response(
backend-1    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 154, in serialize_response
backend-1    |     raise ResponseValidationError(
backend-1    | fastapi.exceptions.ResponseValidationError: 12 validation errors:
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'aac'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'state_aac'), 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'order'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Kidney_Disease', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'aac'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'state_aac'), 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'order'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    |   {'loc': ('response', 'categories', 'rfandscreening', 'measures', 'Met_Cervical_Screen', 'unit'), 'msg': 'field required', 'type': 'value_error.missing'}
backend-1    | 

```

**Comment by falquaddoomi** [comment]
Ok, I think I have a better idea of what was going on the other day when it seemed you had to run `./run_stack.sh down -v` to purge the database before it would reload. Docker Compose tries to only restart services that it detects have changed, and based on your log it kept `ecco-db-1` running, which makes sense since adding a database dump to the `db-exports` folder doesn't register to it as a change to the service. That also explains why it works for me -- since I generated the dump, I had to first load it, so I never notice that the db doesn't get restarted in order to load it.

The short answer is that you have to somehow trigger the database container to restart in order for it to pick up a new database dump, since it does that at load time (at the moment, at least). I also noticed that `memcached` wasn't restarting either, which would probably also be a good idea to restart so that you're not dealing with stale cached data.

Try running `/run_stack.sh restart db memcached` and seeing if that resolves the issue.

**Comment by vincerubinetti** [comment]
Cool, glad that could help. Fwiw I don't think it's a big deal to have to do a manual teardown when there's a new db. I did forget about that a few times, but now I know, and it's only you me and maybe Sean who will be running this locally.

**Comment by vincerubinetti** [comment]
Okay looks good to me. 

> TODO: add state and source to /fips-value

This one is done, then.

> TODO: hard-code state_value instead of calculating it

This one isn't yet, it seems like.

**Comment by falquaddoomi** [comment]
> TODO: hard-code state_value instead of calculating it
> This one isn't yet, it seems like.

Right, thanks for the reminder. I'll add that ASAP and then we can hopefully get this PR out the door. FYI, I'll follow it with a testing PR that finally fixes tests and adds some much-needed data/metadata agreement checks.

**Comment by falquaddoomi** [comment]
Recent changes:
- added import commands, db dump for the Colorado Cancer Center ("CCC") state-level values sheet
  - sheet was provided in https://github.com/colorado-cancer-center/ecco/issues/78#issuecomment-2349835463, but manually modified by me to agree with the 2024-09 CiF release
- by-county endpoint now retrieves from the CCC data;
  - `state_value` can now be null and is typically not undefined
  - `state_aac` is always null, since we lack data from the CCC for it
- slightly modified frontend `PageCounty.vue` to deal with `state_value` being `null` and not just `undefined`
  - (please modify as you see fit, just wanted to see if I could get the page to work)

Note that the CCC data only includes a small subset of summary stats compared to the total, so expect to see that lots of the state-level values will be null.

A minor note: I left in the logic for computing statistics by taking a per-county average (or other statistic, depending on the type), but it's disabled with a flag. If we ever want to use those stats as a fallback, I've added a `state_stat_source` field to the response that's set to `"ccc"` if it's from our hardcoded data, `"computed"` if it's generated, or `null` if it's not included at all. I could imagine it being useful for specific measure categories, e.g. the trend data, where we lack hardcoded data and taking the median/mode(?) across all counties would make sense.

**Comment by vincerubinetti** [comment]
Looks good, I spot checked the state values and they seem to match what Cydney gave us [here](https://github.com/colorado-cancer-center/ecco/issues/78#issuecomment-2349835463).

>sheet was provided in https://github.com/colorado-cancer-center/ecco/issues/78#issuecomment-2349835463, but manually modified by me to agree with the 2024-09 CiF release

Can't tell if this means this PR closes #94, or if it just sets it up so the future PR for it is easier? Looks like there's a db dump for that data.

**Comment by falquaddoomi** [comment]
> Can't tell if this means this PR closes https://github.com/colorado-cancer-center/ecco/issues/94, or if it just sets it up so the future PR for it is easier? Looks like there's a db dump for that data.

Good point; half of that issue, integrating the 2024-09 CiF data + metadata changes was addressed in this PR, and I've updated the description in that issue accordingly. The other half, adding tests, will be included in a future PR.

I'll go ahead and merge this PR now; thanks for your work on it.

**Review by falquaddoomi — APPROVED** [review]
I think everything in this PR is working, although it ended up being a bit larger than I expected (my fault).

**Pull request merged**
