### PR TITLE
Frontend tweaks

### LINKED ISSUE #100: Misc frontend tweaks
- show total county population at the top of the county page "basic" view, to give context to the charts
- in "all" view, for measure categories, link to the /sources page like we do from the main page
- remove "see all data" button from location tooltip
- bold "Click on a county or location to see more info"
- change ? to n.d. in legend

### PR DESCRIPTION
**Pull request by falquaddoomi**
Closes #100 

During our meeting on Nov. 5th, we made some live changes to the county snapshot basic view, and discussed other minor changes to the frontend. This PR addresses those.

- remove "Diabetes RX" from risk factors
- change the title of the screening chart from "Adults Recommended for Cancer Screening (%)" to "Adults Up-to-Date with Screening"
- show total county population at the top of the county page "basic" view, to give context to the charts
- in "all" view, for measure categories, link to the /sources page like we do from the main page
- remove "see all data" button from location tooltip
- bold "Click on a county or location to see more info"
- change ? to n.d. in legend

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Do you mind if I just add this stuff in here too, it's all in the same category of minor/quick frontend tweaks https://github.com/colorado-cancer-center/ecco/issues/100

**Review by vincerubinetti — APPROVED** [review]
Please take a look at the changes I pushed.

**Comment by falquaddoomi** [comment]
Unfortunately I can't formally review my own PR, but I looked over your changes locally; they look good and seemed to work for me. One very minor thing, maybe you could put "ND" instead of "n.d." for the "no data" element in the legend? It'd save you some characters.

Regarding data: I see that you're referencing `sociodemographics.measures.Total.state_value`, which currently isn't in our input spreadsheet and thus not in the database, but I can add it in. Unfortunately it seems the state population was most recently estimated in July 2023, https://www.census.gov/quickfacts/CO, which may be a bit behind our county-level data, but I guess we can make a note of that somewhere. I made a few changes to my local database to account for some issues with the cancer state values in the source spreadsheet, too. If you're ok with it, I can add a database dump to this PR that fixes those issues as well as adds the state-level total population value.

**Comment by vincerubinetti** [comment]
I was going to mention that to you, since we should def have that data. We can just comment out the state pop value for now.

**Comment by falquaddoomi** [comment]
I think I still want to update the state-level cancer data at some point, so I'll either add the db dump that does that to this PR or create a new PR with it, if you prefer.

About the state-level population, sure, I can hold off on introducing it in the db until we're ready for it. I can also just add it in and you can re-enable it in the frontend when you're ready to add it. Just let me know which you prefer.

**Comment by vincerubinetti** [comment]
Sounds like it's more work on the backend than the frontend so it's up to you. Can easily add the little state-wide population badge back in.

**Comment by falquaddoomi** [comment]
FYI, the latest db dump just includes fixing the factors for the state-level statistics, so that they match the SCP factors. You should now see that the state-level values appear for all the sites under cancer incidence and mortality, not just a few.

**Comment by vincerubinetti** [comment]
LGTM

**Pull request merged**
