### PR TITLE
Adds backend, frontend support for per-county reports

### PR DESCRIPTION
**Pull request by falquaddoomi**
This PR adds an endpoint for `/stats/by-county/<fips>/`, which retrieves all measures and their values for a specific county given by its full FIPS (i.e., `08` for Colorado plus the county's FIPS).

For example, to retrieve the values for Boulder County you'd query the endpoint `/stats/by-county/08013`.

Addresses #76, but the issue is incomplete until the frontend support has been added as well.

### CODE REVIEW

**Review by vincerubinetti — APPROVED** [review]
Looked at your code, and integration with frontend seems to work as expected (though I did have to run `down -v` fwiw, maybe something to double check), so LGTM. 

Please review and test my changes then feel free to merge.

**Comment by falquaddoomi** [comment]
> Looked at your code, and integration with frontend seems to work as expected (though I did have to run down -v fwiw, maybe something to double check), so LGTM.

What was the behavior that lead you to have to run that? Also, just FYI the database doesn't hot-reload if you're still running the stack and, e.g., change branches. You'd have to first bring down the stack then relaunch it using `run_stack.sh`, but it should always reload the database now, not just when you've destroyed all volumes using `-v`.

Just checked, and I'm seeing the county page showing up. Looks good, although I suppose we'll want to display the state-level measure value alongside each county-level measure value to match the mockups. Perhaps you can take a pass at trying to compute that on the frontend, and if it doesn't make sense I can try to dig up the state-level data and serve that from the backend, too.

Would it be a lot of work to add the name of the county instead of just "County" to the window title? I realize I have no user stories or anything to back this up so feel free to ignore this, but for me I could imagine wanting to compare some counties and wanting to be able to find each county by the name of the tab.

**Comment by falquaddoomi** [comment]
@vincerubinetti Regarding the last two commits:

- [dd5ab52](https://github.com/colorado-cancer-center/ecco/pull/92/commits/dd5ab52057bf6e251338103aa45c53edcad3c3a3): after looking at your county summary page, I noticed that the trends were numbers; that was my bad, as I forgot that the trends tables need to be handled differently because they're views. Anyway, I fixed the backend so that the SCP trends measures now return "falling", "rising", "stable", etc. Blank values are filtered out from being returned, since they just mean we don't have data for that county and I presume people would assume the lack of a row would mean we didn't have data on it. Also, I hope it's ok that I updated the frontend type definition for `_CountyData` to allow both numbers and strings for `value`.
- [aa2a93f](https://github.com/colorado-cancer-center/ecco/pull/92/commits/aa2a93f3b60b516ed162cb74462361c4b3d02c52)): I realized that some of our models have factors that I wasn't taking into account when returning the summaries; this was causing the last entry in the database for the given county to be returned as the value. This commit filters measures with factors to whatever their default value is, i.e. "All" for sex, stage, race, and age for the SCP models. IMHO it's probably not necessary and more confusing to allow users to choose the values for factors themselves, but we can add that if there's a need.

**Comment by vincerubinetti** [comment]
> What was the behavior that lead you to have to run that? 

Well it was the first time running the run script since I got to Colorado. Nothing should've been running beforehand because I did a full restart of my laptop. It happened on Monday... I should've told you so you could debug before I did the tear down, sorry about that.

> Perhaps you can take a pass at trying to compute that on the frontend

I could do that, but I believe I'd have to make separate API calls for each measure to calculate the total. Might be prudent to do it in the backend, perhaps a new endpoint to get the state totals? Also, of the "basic" measures shown on the county page, only a few of them are absolute counts (where I could derive them on the frontend). So, maybe we should do a new PR for the totals #78 since it's going to require a deeper dive (mostly on the backend).

> Anyway, I fixed the backend so that the SCP trends measures now return "falling", "rising", "stable", etc.

I think this is good. Can we make the regular values endpoint work this way too? Because currently I'm [hardcoding it in the frontend](https://github.com/colorado-cancer-center/ecco/blob/main/frontend/src/api/index.ts#L226). If you just return a string, I can update the map component to break that into a colored enumeration.

> Would it be a lot of work to add the name of the county instead of just "County" to the window title? 

Done.

> IMHO it's probably not necessary and more confusing to allow users to choose the values for factors themselves,

I agree, let's wait until someone asks.

**Comment by falquaddoomi** [comment]
> I could do that, but I believe I'd have to make separate API calls for each measure to calculate the total. Might be prudent to do it in the backend, perhaps a new endpoint to get the state totals? Also, of the "basic" measures shown on the county page, only a few of them are absolute counts (where I could derive them on the frontend). So, maybe we should do a new PR for the totals https://github.com/colorado-cancer-center/ecco/issues/78 since it's going to require a deeper dive (mostly on the backend).

Yeah, the more I think about it, the more it makes sense to return it from the backend. I'll add it to this PR for the by-county stats for now so that we can complete the feature; we can expand it later, perhaps in a separate PR as you suggested.

> Maybe the endpoint could return something like { order: ["falling", "stable", "rising"] }. Or, since this is mainly a frontend concern, I could just hard code that order list. Still a hardcoding, but this way the frontend could still display the string values without it, they just might be in the wrong order.

Sure, I think that's doable. The easiest place to return it for me would be alongside the `unit` field from `fips-value` when the unit is an ordinal.

I could also return it from the `measures` endpoint if you need it earlier in the page loading process; it makes some sense to return it there since it's metadata about the measures. I'd have to think a little bit about where to put it there, though...I could perhaps stick it in the measure category level. While I'm at it, I might also move the factors out of the measure and put them in the measure category, since AFAIK all measures share the same factors in a given measure category.

Let me think about it for a bit if we go with updating the `measures` endpoint; I'll provide a suggested schema before I start implementing it so you can comment on it.

**Comment by vincerubinetti** [comment]
> Sure, I think that's doable. The easiest place to return it for me would be alongside the unit field from fips-value when the unit is an ordinal.

If you want to and if it's not a big deal. Again I think in this case it'd actually make sense to hard code it in the frontend. Anyone using the API directly will know what they mean and what their logical "order" is from their strings.

**Comment by vincerubinetti** [comment]
Screenshot 2024-09-10 at 5 30 59 PM

So I'm still getting integers for `value`, meaning that I'd still need to have the `{ 1: "Falling", 2: "Stable", 3: "Rising" }` map in the frontend. Did you intend to include that change in this PR? It seems like it'd need a change in the model from `float` to `float | string` which I'd imagine would require a bunch of other changes. In the long run it makes sense to me that it could be a string for enumerated values, but in the short term maybe you could just return something like `"value_map": { ...see above... }` instead of `order`?

Also something odd is going on with the min/max there. I'm not using these returned values in the frontend but I figured I'd mention it.

> since they're ordinal-valued, avg_value is the median value

I'm not a data scientist, but would it make sense to do the "mode" here instead? Like, which value appears the most often?

**Comment by falquaddoomi** [comment]
> So I'm still getting integers for value, meaning that I'd still need to have the { 1: "Falling", 2: "Stable", 3: "Rising" } map in the frontend. Did you intend to include that change in this PR? It seems like it'd need a change in the model from float to float | string which I'd imagine would require a bunch of other changes. In the long run it makes sense to me that it could be a string for enumerated values, but in the short term maybe you could just return something like "value_map": { ...see above... } instead of order?

I hadn't thought to change it, but sure, I can change the value for the trend models to be the string rather than its ordinal value; I just tested it out locally and it didn't seem to create issues in the backend, but the frontend would have to be updated to deal with the strings, of course.

Regarding how to return the ordering to the frontend, I'm open to whatever you prefer; I can return the `value_map` dict you suggested, although dicts don't have an inherent ordering, so the user will just have to assume the indices are in ascending order or something. We can also go with the backend returning strings for the trends model's values and leave the existing `order` list in place.

> Also something odd is going on with the min/max there. I'm not using these returned values in the frontend but I figured I'd mention it.

Right, good catch; I was returning the min/max of the AAR column for the SCP incidence/deaths data for trends models, not the min/max of the ordinal value. I've updated it accordingly; it now returns the min and max only over regions that have a value for the trend column (many don't, and `0` as the min isn't very useful...).

> I'm not a data scientist, but would it make sense to do the "mode" here instead? Like, which value appears the most often?

Neither am I, heh. Well, I guess it comes down to whether you consider 51% of counties being "falling" and 49% being "rising" as "falling" or "stable" -- I'd consider it "stable" (the median), but I could see the argument for "falling". If this were a categorical value (i.e., just labels without any ordering) the mode would make the most sense, but I'm torn since it's ordinal.

**Comment by falquaddoomi** [comment]
One last thing: perhaps have the county tooltip appear over the legends? I noticed it going under the legends a bit during the demo.

**Comment by vincerubinetti** [comment]
It should just be a z-index change, but can we do that in the next PR? I've noted it in #93

**Pull request merged**
