### PR TITLE
Adds SCP model, data, and various other refactors

### LINKED ISSUE #14: Create data resource for cancer incidence and mortality broken down by ....
I'm getting data on incidence and mortality broken down by below. The data will be available as a long-form table (should be a few million rows). I'll share when I'm done. The data look like:

|          County          |  FIPS  | Age-Adjusted_Incidence_Raterate_note_-_cases_per_100,000 | Lower_95%_Confidence_Interval | Upper_95%_Confidence_Interval | CI_Rankrank_note | Lower_CI_CI_Rank | Upper_CI_CI_Rank | Average_Annual_Count | Recent_Trend | Recent_5-Year_Trend_trend_note_in_Incidence_Rates | Lower_95%_Confidence_Interval.1 | Upper_95%_Confidence_Interval.1 | year | stateFIPS | sex | stage | race | cancer | area_type | age |
|--------------------------|--------|----------------------------------------------------------|-------------------------------|-------------------------------|------------------|------------------|------------------|----------------------|--------------|---------------------------------------------------|---------------------------------|---------------------------------|------|-----------|-----|-------|------|--------|-----------|-----|
| Alameda County(7)        | 6001.0 | 371.5                                                    | 367.5                         | 375.5                         | 47               |  41              |  51              | 6890.0               | falling      | -1.4                                              | -2.6                            |  -1.0                           | 0    | 08        | 0   | 999   | 38   | 076    | county    | 009 |
| Modoc County(7)          | 6049.0 | 310.6                                                    | 266.1                         | 361.2                         | 55               |  39              |  58              | 44.0                 | stable       | -1.4                                              | -3.4                            |  0.5                            | 0    | 08        | 1   | 999   | 48   | 090    | county    | 136 |
| Butte County(7)          | 6007.0 | 474.9                                                    | 463.0                         | 486.9                         | 3                |  1               |  6               | 1347.0               | falling      | -0.5                                              | -0.9                            |  -0.1                           | 0    | 08        | 2   | 211   | 28   | 057    | county    | 009 |
| Alameda County(7)        | 6001.0 | 371.5                                                    | 367.5                         | 375.5                         | 47               |  41              |  51              | 6890.0               | falling      | -1.4                                              | -2.6                            |  -1.0                           | 0    | 08        | 0   | 211   | 48   | 001    | county    | 157 |
| Humboldt County(7)       | 6023.0 | 435.8                                                    | 421.4                         | 450.7                         | 12               |  4               |  23              | 755.0                | falling      | -1.0                                              | -1.5                            |  -0.4                           | 0    | 08        | 2   | 211   | 07   | 066    | county    | 157 |
| Riverside County(7)      | 6065.0 | 389.6                                                    | 386.2                         | 393.0                         | 35               |  31              |  42              | 10550.0              | falling      | -0.8                                              | -1.0                            |  -0.7                           | 0    | 08        | 0   | 211   | 07   | 053    | county    | 009 |
| Stanislaus County(7)     | 6099.0 | 422.3                                                    | 414.6                         | 430.0                         | 16               |  12              |  25              | 2390.0               | stable       | -0.2                                              | -0.5                            |  0.1                            | 0    | 08        | 2   | 211   | 05   | 057    | county    | 001 |
| San Bernardino County(7) | 6071.0 | 393.8                                                    | 390.0                         | 397.7                         | 34               |  29              |  39              | 8326.0               | falling      | -0.8                                              | -1.0                            |  -0.6                           | 0    | 08        | 1   | 999   | 05   | 090    | county    | 006 |
| Nevada County(7)         | 6057.0 | 402.4                                                    | 387.6                         | 417.6                         | 29               |  15              |  41              | 694.0                | falling      | -1.3                                              | -1.9                            |  -0.7                           | 0    | 08        | 1   | 211   | 48   | 080    | county    | 157 |
| Marin County(7)          | 6041.0 | 442.0                                                    | 432.3                         | 451.9                         | 9                |  5               |  15              | 1754.0               | falling      | -0.6                                              | -0.9                            |  -0.4                           | 0    | 08        | 2   | 999   | 38   | 020    | county    | 136 |
| Glenn County(7)          | 6021.0 | 509.8                                                    | 475.3                         | 546.2                         | 1                |  1               |  5               | 170.0                | stable       | 0.2                                               | -0.6                            |  1.1                            | 0    | 08        | 1   | 999   | 07   | 090    | county    | 009 |
| Lassen County(7)         | 6035.0 | 346.7                                                    | 319.0                         | 376.2                         | 53               |  35              |  57              | 122.0                | stable       | 0.3                                               | -0.8                            |  1.6                            | 0    | 08        | 2   | 211   | 28   | 035    | county    | 009 |
| Marin County(7)          | 6041.0 | 442.0                                                    | 432.3                         | 451.9                         | 9                |  5               |  15              | 1754.0               | falling      | -0.6                                              | -0.9                            |  -0.4                           | 0    | 08        | 2   | 999   | 38   | 515    | county    | 001 |
| Alameda County(7)        | 6001.0 | 371.5                                                    | 367.5                         | 375.5                         | 47               |  41              |  51              | 6890.0               | falling      | -1.4                                              | -2.6                            |  -1.0                           | 0    | 08        | 2   | 211   | 38   | 090    | county    | 136 |
| Solano County(7)         | 6095.0 | 415.6                                                    | 407.7                         | 423.6                         | 21               |  14              |  30              | 2228.0               | falling      | -1.5                                              | -2.5                            |  -1.0                           | 0    | 08        | 1   | 999   | 48   | 055    | county    | 009 |
| Sacramento County(7)     | 6067.0 | 412.3                                                    | 407.9                         | 416.7                         | 22               |  18              |  28              | 7022.0               | falling      | -1.3                                              | -1.8                            |  -1.1                           | 0    | 08        | 1   | 211   | 07   | 400    | county    | 001 |
| Napa County(7)           | 6055.0 | 410.5                                                    | 397.3                         | 424.1                         | 24               |  13              |  37              | 776.0                | falling      | -2.6                                              | -4.0                            |  -1.7                           | 0    | 08        | 1   | 211   | 28   | 040    | county    | 136 |
| Mono County(7)           | 6051.0 | 250.6                                                    | 217.8                         | 287.4                         | 58               |  55              |  58              | 47.0                 | stable       | -1.2                                              | -3.4                            |  1.3                            | 0    | 08        | 1   | 999   | 05   | 076    | county    | 157 |
| Glenn County(7)          | 6021.0 | 509.8                                                    | 475.3                         | 546.2                         | 1                |  1               |  5               | 170.0                | stable       | 0.2                                               | -0.6                            |  1.1                            | 0    | 08        | 2   | 211   | 38   | 047    | county    | 001 |
| San Diego County(7)      | 6073.0 | 418.5                                                    | 415.5                         | 421.5                         | 18               |  15              |  24              | 15343.0              | rising       | 1.1                                               | 0.3                             |  1.7                            | 0    | 08        | 2   | 211   | 48   | 053    | county    | 006 |

### LINKED ISSUE #16: Scrape state cancer profiles
https://gist.github.com/seandavi/3d3136aaf66b0b58e2f1906085415312

### PR DESCRIPTION
**Pull request by falquaddoomi**
This PR introduces the State Cancer Profiles models and data, derived from Sean's scraped data.

The PR adds the following measure categories:
- "State Cancer Profiles: Incidence"
- "State Cancer Profiles: Death"

Each model is stratified on the following categorical variables: Sex, Stage, Race, and Age.

The "trends" categories are currently commented out; to enable them, uncomment https://github.com/colorado-cancer-center/ecco/compare/issue-14-scp-dataset?expand=1#diff-1a13f5006d44e335e8a1c53f034298a8e24827093b6244dc8b5df2edd89249ccR81-R82 (if that link doesn't work, lines 81 and 82 in `backend/app/models/scp.py`). The "trend" measure categories return the following values for each trend ordinal (colors from Jan):
- (no data): 0 (should be gray/"no data" color)
- "falling": 1 (should be blue)
- "stable": 2 (should be green)
- "rising": 3 (should be red)

Importantly, the PR now makes all relevant API endpoints' "value" field nullable, though no data currently will return null for the time being.

The PR also includes some refactors of the metadata associated with models.

Closes #14.

Closes #16.

### CODE REVIEW

**Comment by falquaddoomi** [comment]
@vincerubinetti just FYI, there are cases with the new data where it's not possible to choose a default value for a factor that's present across all the measure categories. For example, for the measure category "State Cancer Profiles: Incidence", the measure "Childhood (Ages <15, All Sites)" only has "Age < 15" as an option, but none of the other measure categories have that option.

Perhaps, as a quick fix, if there's just one option in a factor dropdown, it should just be selected by default?

This is part of a wider issue with factors in these tables: some of them have rows explicitly labeled "All", and some don't. Ideally we'd have a "no selection" option for every factor that would not filter on the factor, but there are complications with that approach that I've documented in issue #57.

**Comment by vincerubinetti** [comment]
> Perhaps, as a quick fix, if there's just one option in a factor dropdown, it should just be selected by default?

Unless I'm misunderstanding, I believe this should already happen per this line:
https://github.com/colorado-cancer-center/ecco/blob/main/frontend/src/pages/PageHome.vue#L579

**Comment by falquaddoomi** [comment]
> > Perhaps, as a quick fix, if there's just one option in a factor dropdown, it should just be selected by default?
> 
> Unless I'm misunderstanding, I believe this should already happen per this line: https://github.com/colorado-cancer-center/ecco/blob/main/frontend/src/pages/PageHome.vue#L579

Huh, yeah, that looks like what I was asking for, and after you mentioned it I wasn't able to reproduce the behavior. I've figured it out, though; this should reproduce it:
1. select the measure category "State Cancer Profiles: Incidence"
2. select one of the cancer measures, e.g. "Leukemia"
3. the Age will become "<50", since that's the first option
4. select one of the childhood cancer measures, e.g. "Childhood (Ages <15, All Sites)"
5. the Age dropdown will contain "None selected".
6. Selecting the only Age option, "Age < 15", will show data on the map
7. Switching the measure category back to a cancer will again show "None selected"

I assume now that this is because the logic you linked above runs when factors change, but when you switch between measure categories it's not being run. I assume the existing selection, e.g. "Age < 15" is being preserved even though it doesn't exist in the new measure category's Age options.

**Comment by vincerubinetti** [comment]
I'll fix that. That top-level watcher is only run when the factor options change, but there's a dynamic watcher created within it that runs when the selected factor changes that can be updated to include setting a fallback. That will come with the tradeoff that setting the fallback will override what was previously in the url; so if the user has a specific factor value selected, then goes to another factor (and the fallback gets set), then back to the first factor, their original selected value won't be remembered.

**Comment by vincerubinetti** [comment]
Was going to add my frontend changes to this, but I'll token-approve this for now and review the changes here later for any issues.

**Review by vincerubinetti — APPROVED** [review]

**Pull request merged**
